### ISSUE TITLE
ModuleNotFoundError: No module named 'ont_fast5_api.fast5_interface'

### ISSUE THREAD

**Issue by ChrisFearn97** [shimlab/NanoSplicer#1]
Dear all,
I am interested seeing if NanoSplicer may be able to help in my research however I am having trouble using the NanoSplicer.py file. 
I have installed all the the dependencies to a conda environment however when I try to run the NanoSplicer.py I am met with the following:
Traceback (most recent call last):
  File "NanoSplicer.py", line 62, in <module>
    from ont_fast5_api.fast5_interface import get_fast5_file
ModuleNotFoundError: No module named 'ont_fast5_api.fast5_interface'

Any advice on how to fix this would be much appreciated.

Kind regards,

Chris

**Comment by youyupei** [comment]
Hi Chris,

It seems the package "ont_fast5_api" is missing. Could you try install it with "pip"? e.g. run "pip3 install  ont_fast5_api".

**Comment by ChrisFearn97** [comment]
Hi there,

Thankyou for the quick response.  I was unsuccessful using pip however I have managed to fix the issue using conda.  It woud appear that conda defaulted to installing an old version of the "ont_fast5_api" and so I have specified that it installs a more up to date version. 

I now have a new issue though that maybe you can help with?  When running NanoSplicer.py I am now met with the following:

Traceback (most recent call last):
  File "NanoSplicer.py", line 1299, in <module>
    main()
  File "NanoSplicer.py", line 300, in main
    jwr_df = pd.read_hdf(pd_file, key = 'data')
  File "/nfs/anaconda3/envs/nanosplice/lib/python3.7/site-packages/pandas/io/pytables.py", line 423, in read_hdf
    auto_close=auto_close,
  File "/nfs/anaconda3/envs/nanosplice/lib/python3.7/site-packages/pandas/io/pytables.py", line 867, in select
    return it.get_result()
  File "/nfs/anaconda3/envs/nanosplice/lib/python3.7/site-packages/pandas/io/pytables.py", line 1921, in get_result
    results = self.func(self.start, self.stop, where)
  File "/nfs/anaconda3/envs/nanosplice/lib/python3.7/site-packages/pandas/io/pytables.py", line 851, in func
    return s.read(start=_start, stop=_stop, where=_where, columns=columns)
  File "/nfs/anaconda3/envs/nanosplice/lib/python3.7/site-packages/pandas/io/pytables.py", line 3161, in read
    values = self.read_array(f"block{i}_values", start=_start, stop=_stop)
  File "/nfs/anaconda3/envs/nanosplice/lib/python3.7/site-packages/pandas/io/pytables.py", line 2818, in read_array
    ret = node[0][start:stop]
  File "/nfs/anaconda3/envs/nanosplice/lib/python3.7/site-packages/tables/vlarray.py", line 677, in __getitem__
    return self.read(start, stop, step)[0]
  File "/nfs/anaconda3/envs/nanosplice/lib/python3.7/site-packages/tables/vlarray.py", line 821, in read
    outlistarr = [atom.fromarray(arr) for arr in listarr]
  File "/nfs/anaconda3/envs/nanosplice/lib/python3.7/site-packages/tables/vlarray.py", line 821, in <listcomp>
    outlistarr = [atom.fromarray(arr) for arr in listarr]
  File "/nfs/anaconda3/envs/nanosplice/lib/python3.7/site-packages/tables/atom.py", line 1224, in fromarray
    return pickle.loads(array.tostring())
ValueError: unsupported pickle protocol: 5

I have read that pickle protocol 5 is supported in python versions 3.8+ however I am unable to upgrade the version of python in the environment due to clashes with tombo. I have also tried installing pickle5 but this does not seem to have fixed the issue.  Thankyou for your continued help. 

kind regards,

Chris

**Comment by youyupei** [comment]
Hi Chris, 

I have recently added an instruction for the conda environment: https://github.com/shimlab/NanoSplicer#conda-environment. Feel free to let me know if the problem persist under this environment.
