### ISSUE TITLE
OverflowError: value too large to convert to int

### ISSUE THREAD

**Issue by martinhaagmans** [shimlab/NanoSplicer#16]
```
python JWR_checker.py aligned_nobarcode.bam NanoSplicer.hdf5

Warning: Mismatches are not explicitly labeled in the CIGAR from the input BAM file.
  The JAQs can still be calculated but mismatched bases will be treated as matched bases.
  It is recommended to update the mapping setting (e.g., use '--eqx' option in minimap2)
  to label the mismatches in CIGAR.
  Searching for JWRs ...
  Calculating JAQ for 80764086 JWRs found
  80764500it [10:47:04, 180.72it/s]Traceback (most recent call last):
    File "/net/beegfs/scratch/mhaagmans/data/RNA_diagnostiek/dRNA_clair/NanoSplicer/bin/JWR_checker.py", line 304, in <module>
      main()
    File "/net/beegfs/scratch/mhaagmans/data/RNA_diagnostiek/dRNA_clair/NanoSplicer/bin/JWR_checker.py", line 296, in main
      [d.to](http://d.to/)_hdf(param.outfile, 'data')
    File "/trinity/home/mhaagmans/miniconda3/envs/NanoSplicer/lib/python3.7/site-packages/pandas/core/generic.py", line 2718, in to_hdf
      encoding=encoding,
    File "/trinity/home/mhaagmans/miniconda3/envs/NanoSplicer/lib/python3.7/site-packages/pandas/io/pytables.py", line 314, in to_hdf
      f(store)
    File "/trinity/home/mhaagmans/miniconda3/envs/NanoSplicer/lib/python3.7/site-packages/pandas/io/pytables.py", line 306, in <lambda>
      dropna=dropna,
    File "/trinity/home/mhaagmans/miniconda3/envs/NanoSplicer/lib/python3.7/site-packages/pandas/io/pytables.py", line 1136, in put
      dropna=dropna,
    File "/trinity/home/mhaagmans/miniconda3/envs/NanoSplicer/lib/python3.7/site-packages/pandas/io/pytables.py", line 1785, in _write_to_group
      track_times=track_times,
    File "/trinity/home/mhaagmans/miniconda3/envs/NanoSplicer/lib/python3.7/site-packages/pandas/io/pytables.py", line 3232, in write
      self.write_array(f"block{i}_values", blk.values, items=blk_items)
    File "/trinity/home/mhaagmans/miniconda3/envs/NanoSplicer/lib/python3.7/site-packages/pandas/io/pytables.py", line 3078, in write_array
      vlarr.append(value)
    File "/trinity/home/mhaagmans/miniconda3/envs/NanoSplicer/lib/python3.7/site-packages/tables/vlarray.py", line 528, in append
      self._append(nparr, nobjects)
    File "tables/hdf5extension.pyx", line 2033, in tables.hdf5extension.VLArray._append
  OverflowError: value too large to convert to int
  80764500it [10:51:43, 2065.39it/s]
```

Is there anything I can do? It was an RNA004 ONT run

**Comment by youyupei** [comment]
Hi @martinhaagmans , unfortunately, Nanosplicer does not support direct RNA sequencing data at the moment, but we are working on it. Will update you once we have any progress
