### ISSUE TITLE
unable to run NanoSplicer.py 

### ISSUE THREAD

**Issue by anshulbudhraja** [shimlab/NanoSplicer#5]
The code runs very well in the JWR_checker.py and JWR_subset.py, and produces non-empty .h5 and .h5.csv file with more than 100,000 JWRs but it seems that file is empty for NanoSplicer or the output of NanoSplicer is empty? (I did give the full path to the .h5 output of JWR_subset)

The error from NanoSplicer.py :
```
running process
^M0it [00:00, ?it/s]Traceback (most recent call last):
  File "/home/anshul/softwares/NanoSplicer/bin/NanoSplicer.py", line 1441, in <module>
    main()
  File "/home/anshul/softwares/NanoSplicer/bin/NanoSplicer.py", line 425, in main
    pd.concat([x.result() for x in futures]).to_csv(error_fn)
  File "/home/anshul/miniconda3/envs/NanoSplicer/lib/python3.7/site-packages/pandas/util/[decorators.py](http://decorators.py/)", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/anshul/miniconda3/envs/NanoSplicer/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 304, in concat
    sort=sort,
  File "/home/anshul/miniconda3/envs/NanoSplicer/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 351, in init
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
^M0it [00:00, ?it/s]
Command exited with non-zero status 1
```

The command used :
```
python3 /home/anshul/softwares/NanoSplicer/bin/NanoSplicer.py -i /scratch/anshul/NanoSplicer_trials/Genome_mapped/Stringtie2-noRef.annotated_code_u_N100_mapped_sorted.bam -f /scratch/anshul/NanoSplicer_trials/JWR_subset/defaultVal/ -r /home/refs/human/dna/hg38_chrIS.fa -o /scratch/anshul/NanoSplicer_trials/NanoSplice/Stringtie2-noRef.annotated_code_u_N100_mapped --threads 16 /scratch/anshul/NanoSplicer_trials/JWR_subset/defaultVal/Stringtie2-noRef.annotated_code_u_N100_mapped_jwrSubset.h5
```

The output of JWR_subset:
```
$ wc -l /scratch/anshul/NanoSplicer_trials/JWR_subset/defaultVal/Stringtie2-noRef.annotated_code_u_N100_mapped_jwrSubset.h5.csv
124379 /scratch/anshul/NanoSplicer_trials/JWR_subset/defaultVal/Stringtie2-noRef.annotated_code_u_N100_mapped_jwrSubset.h5.csv
```

**Comment by youyupei** [comment]
Hi @anshulbudhraja,

Thanks for being interested in NanoSplicer and sorry for the late late reply. Your error message usually means that the path you provided by `-f` did NOT contain any `.fast5` files (note that they have to be suffixed by `.fast5`), or the fast5 files did not match the reads used in the previous steps. You may double-check the files in `/scratch/anshul/NanoSplicer_trials/JWR_subset/defaultVal/`, and feel free to let me know if it is not the case.

Regards,
Yupei
