### ISSUE TITLE
Floating point error in NanoSplicer.py

### ISSUE THREAD

**Issue by sagnikbanerjee15** [shimlab/NanoSplicer#6]
Hello,

I am trying to execute the commands in `scripts.sh`. The first two commands were executed without any error. The last command gives the following error.
```
python3 ../bin/NanoSplicer.py -i example.bam -f fast5s/ -r sequins_genome.fa JWR_subset.h5
Traceback (most recent call last):
  File "/NanoSplicer/examples/../bin/NanoSplicer.py", line 65, in <module>
    from tombo import tombo_helper, tombo_stats, resquiggle
  File "/opt/conda/lib/python3.10/site-packages/tombo/tombo_stats.py", line 84, in <module>
    HALF_NORM_EXPECTED_VAL = stats.halfnorm.expect()
  File "/opt/conda/lib/python3.10/site-packages/scipy/stats/_distn_infrastructure.py", line 2949, in expect
    dub = integrate.quad(fun, d, ub, **kwds)[0]
  File "/opt/conda/lib/python3.10/site-packages/scipy/integrate/_quadpack_py.py", line 463, in quad
    retval = _quad(func, a, b, args, full_output, epsabs, epsrel, limit,
  File "/opt/conda/lib/python3.10/site-packages/scipy/integrate/_quadpack_py.py", line 577, in _quad
    return _quadpack._qagie(func,bound,infbounds,args,full_output,epsabs,epsrel,limit)
  File "/opt/conda/lib/python3.10/site-packages/scipy/stats/_distn_infrastructure.py", line 2926, in fun
    return x * self.pdf(x, *args, **lockwds)
  File "/opt/conda/lib/python3.10/site-packages/scipy/stats/_distn_infrastructure.py", line 2102, in pdf
    place(output, cond, self._pdf(*goodargs) / scale)
  File "/opt/conda/lib/python3.10/site-packages/scipy/stats/_continuous_distns.py", line 3956, in _pdf
    return np.sqrt(2.0/np.pi)*np.exp(-x*x/2.0)
FloatingPointError: underflow encountered in exp

```

Could you please look into this?

Thank you.

**Comment by youyupei** [comment]
Hi @sagnikbanerjee15,

Sorry for the late reply. Based on your error message, it seems the error happened when NanoSplicer was trying to import `tombo.stats`. Would you be able to check whether you could start a new python3 session and run `from tombo import tombo_stats`? If not, I would suggest re-install `tombo`. 

Regards,
Yupei
